### ISSUE TITLE
UCDlist 1.4 update

### ISSUE THREAD

**Issue by mbtaylor** [gmantele/ucidy#2]
@gmantele, now that [UCDlist 1.4](https://www.ivoa.net/documents/UCD1+/20210430/) is (officially?) accepted, will you be issuing a matching Ucidy update?  And/or would you like a contributed PR to do that?

**Comment by gmantele** [comment]
Updating Ucidy with the new list will not be an issue. It just means updating the embedded PSV (Pipe Separated Value) file inside the JAR. So, no development here :D

I guess I can already prepare a Pre-Release in GitHub for UCDList-1.4 while waiting for the formal transition to ~~Proposed~~ Endorsed Note. Would that be ok?

**Comment by gmantele** [comment]
I guess I can directly use the (PSV) file of the GitHub repository now: https://github.com/ivoa-std/UCDList/blob/master/ucd-list.txt
It seems include the modifications and is used to generate the LaTeX table inside the UCDList-1.4 document.

**Comment by mbtaylor** [comment]
Thanks Gregory.  It's fine to wait until the EN is fully published, if that's not the case yet.

**Comment by gmantele** [comment]
See discussion about deprecated words: https://github.com/ivoa-std/UCDList/issues/31.

Currently there is a clash between the new list of UCD1+ words and the deprecated words, for
- `meta.ref.ivorn` _=> deprecated but now back in ; reason: ???_
- `pos.resolution` _=> new and different definition from the initially deprecated one_

**Comment by gmantele** [comment]
I finally created a branch - `ucidy-1.2` - including this new list and a corresponding pre-release with the (runnable) JAR.

Before releasing it, I'll have to fix the issue with `meta.ref.ivorn`.

**Comment by gmantele** [comment]
`meta.ref.ivorn` no longer back. So, problem solved :)
