### ISSUE TITLE
Classpath "."

### ISSUE THREAD

**Issue by mbtaylor** [gmantele/ucidy#5]
The manifest of the released jar file is built according to this section of the build.xml file:
```
     <manifest>
       <attribute name="Main-Class" value="${main.runnable.class}"/>
       <attribute name="Class-Path" value="."/>
     </manifest>
```
I don't know why the "." class-path entry is added here. It could present some kind of minor security issue, but the real reason I mention it is because it messes up part of my build system.  I can certainly work round it if required, but if there's no good reason for its presence, could it be removed?

**Comment by gmantele** [comment]
I can't remember whether there was a good reason for this line. Since it works without, I don't see a reason to keep it.
I just removed it (in the branch ucidy-1.2 for the moment).

**Comment by mbtaylor** [comment]
Great, thank you.
