### ISSUE TITLE
stderr output

### ISSUE THREAD

**Issue by mbtaylor** [gmantele/ucidy#6]
For library (as opposed to standalone) use, it's a bit annoying to have output printed direct to stderr.  In the current v1.2-beta, when the class `UCDParser` class is first loaded, the following text is written to stderr:
```
[l.212] ERROR: Skipped deprecated UCD declaration! Cause: The UCD word "meta.ref.ivorn" can not be declared as deprecated! It is already listed among the recognised UCD words.
```
I understand the standards issue that this is referring to, and I guess it will go away when v1.2 is finalised, but if the situation is likely to persist a nicer alternative would be to have such output e.g. sent through the `java.util.logging` system so it can be controlled by client applications.  I can prepare a PR to do this if you like.

**Comment by gmantele** [comment]
You're perfectly right. Actually I thought to do that when releasing its first version, but considering the small size of the library and its low probably to be used I was a bit lazy for less that 10 lines of potential errors/warnings :sweat_smile: 

I just did it. Thank you anyway for having proposed to prepare a PR :wink:

**Comment by mbtaylor** [comment]
Thanks for quick service!
