### ISSUE TITLE
UCD list version reporting

### ISSUE THREAD

**Issue by mbtaylor** [gmantele/ucidy#8]
Feature request: it would be nice if UCDParser instances could report what version of the UCDList standard (i.e. what word lists) they implement, e.g. if `UCDParser.defaultParser.getVersion()` could return "EN-UCD1+-1.4" or "EN-UCD1+-1.4 with Erratum 1" or similar.  Obviously that information would have to be supplied at UCDParser construction time.

**Comment by gmantele** [comment]
Good idea :)

I wonder whether it would not be better at UCDWordList construction time instead (a convenient getter can of course by provided by UCDParser). Why would it be better in UCDParser, according to you?

**Comment by mbtaylor** [comment]
Yes, if you think the UCDWordList is a better place for it that's OK. It should be possible to get information about the versioning of the deprecated words as well as the non-deprecated ones though.

**Comment by gmantele** [comment]
Done. I let you try. I've uploaded a new beta jar version in the GitHub releases: <https://github.com/gmantele/ucidy/releases/tag/v1.2-beta>

From `UCDParser`, you have the following ways to get the default parser versions:

```java
// Get Ucidy version:
UCDParser.getVersion();
// or
UCDParser.UCIDY_VERSION;
// => 1.2

// Get the version of the known words:
UCDParser.defaultParser.knownWords.getVersion();
// => EN-UCD1+-1.4

// Get the version of the deprecated words:
UCDParser.defaultParser.deprecatedWords.getVersion();
// => EN-UCD1+-1.4

// Get all together (you can preview the result by running the main function of UCDParser):
UCDParser.defaultParser.getFullVersion();
/* =>
 * Ucidy version 1.2
 * UCD words version EN-UCD1+-1.4
 * UCD deprecated words version EN-UCD1+-1.4
 */
```

**Comment by mbtaylor** [comment]
Excellent, just what I wanted.  Thanks a lot.
